backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections:

  # Providers

  - label: "Lesson Providers"
    name: "providers"    

    files:
    - file: "pages/providers/providers.json"
      label: "Providers"
      name: "providersFile"      
      
      fields:
      - label: "Providers"
        name: "providersList"
        widget: list
        allow_add: true
        fields:
        - { label: "name", name: "name", widget: "string"}
        - { label: "slug", name: "slug", widget: "string"}

  # Lessons

  - label: "Lessons"
    name: "lessons"      
    
    files:
    - file: "pages/provider/[provider]/lessons/lessons.json"
      label: "Lessons"
      name: "lessonsFile"      
      
      fields:
      - label: "Lessons"
        name: "lessonList"
        widget: list
        allow_add: true
        fields:
        - label: "provider"
          name: "provider"
          widget: "relation"
          collection: "providers"
          search_fields: ["name"]
          value_field: "name"
          display_fields: "name"
        - { label: "title", name: "title", widget: "string"}
        - { label: "slug", name: "slug", widget: "string"}

  # Cards

    # - label: "cards file" # Change to folder structure i.e. lesson/cards
    #   name: "cardsFile"
    #   file: "pages/provider/[provider]/lessons/[lesson]/cards.json"
      
    #   fields:
    #   - label: "cards"
    #     name: "cardList"
    #     widget: list
    #     allow_add: true
    #     fields:
    #           - { label: "term", name: "title", widget: "string"}
    #           - { label: "definition", name: "definition", widget: "string"}
    #           - { label: "author", name: "author", widget: "string"}
    #           - { label: "source", name: "source", widget: "string"}
    #           - { label: "year", name: "year", widget: "string" }
    #           - { label: "Publish Date", name: "date", widget: "datetime" }            