backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "public/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections:

  # Providers

  - label: "Providers"    
    name: "providers"    

    files:
    - file: "pages/providers/providers.json"
      label: "Providers"
      name: "providersFile"      
      
      fields:
      - label: "providers"   
        label_singular: "provider"
        name: "providersList"
        widget: list
        allow_add: true
        fields:
        - { label: "name", name: "name", widget: "string"}
        - { label: "slug", name: "slug", widget: "string"}

  # Authors

  - label: "Authors"    
    name: "authors"    

    files:
    - file: "pages/authors/authors.json"
      label: "Authors"
      name: "authorsFile"      
      
      fields:
      - label: "authors"
        label_singular: "author"
        name: "authorsList"
        widget: list
        allow_add: true
        fields:
        - { label: "name", name: "name", widget: "string"}

  # Lessons

  - label: "Lessons"
    label_singular: "Lesson"
    name: "lessons"

    folder: "api/lessons"
    create: true
    format: "json"  
      
    fields:
    - label: "provider"
      name: "provider"
      widget: "relation"
      collection: "providers"
      search_fields: ["providersList.*.name"]
      display_fields: ["providersList.*.name"]
      value_field: "providersList.*.name"
    - { label: "title", name: "title", widget: "string" }
    - { label: "slug", name: "slug", widget: "string" }
    - { label: "source", name: "source", widget: "string" }
    - label: "Cards"
      label_singular: "Card"
      name: "cards"
      widget: list
      allow_add: true
      fields:
      - { label: "term", name: "term", widget: "string"}
      - { label: "definition", name: "definition", widget: "string" }      
      - { label: "source", name: "source", widget: "string" }
      - { label: "year", name: "year", widget: "string" }
      - label: "author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: ["authorsList.*.name"]
        display_fields: ["authorsList.*.name"]
        value_field: "authorsList.*.name"
    # - label: "Questions"
    # label_singular: "Question"
    # name: "questions"
    # wiget: list
    # allow_add: true
    # fields:
    # - { label: "one", name: "one", widget: "object"}