backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "public/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections:

  # Providers

  - label: "Providers"    
    name: "providers"    

    files:
    - file: "pages/providers/providers.json"
      label: "Providers"
      name: "providersFile"      
      
      fields:
      - label: "providers"   
        label_singular: "provider"
        name: "providersList"
        widget: "list"
        allow_add: true
        fields:
        - { label: "name", name: "name", widget: "string"}
        - { label: "slug", name: "slug", widget: "string"}

  # Authors

  - label: "Authors"    
    name: "authors"    

    files:
    - file: "pages/authors/authors.json"
      label: "Authors"
      name: "authorsFile"      
      
      fields:
      - label: "authors"
        label_singular: "author"
        name: "authorsList"
        widget: "list"
        allow_add: true
        fields:
        - { label: "name", name: "name", widget: "string"}

  # Lessons

  - label: "Lessons"
    label_singular: "Lesson"
    name: "lessons"

    folder: "api/lessons"
    create: true
    format: "json"  
      
    fields:
    - label: "provider"
      name: "provider"
      widget: "relation"
      collection: "providers"
      search_fields: ["providersList.*.name"]
      display_fields: ["providersList.*.name"]
      value_field: "providersList.*.name"
    - { label: "title", name: "title", widget: "string" }
    - { label: "slug", name: "slug", widget: "string" }
    - { label: "source", name: "source", widget: "string" }
    - label: "Cards"
      label_singular: "Card"
      name: "cards"
      widget: "list"
      allow_add: true
      fields:
      - { label: "term", name: "term", widget: "string" }
      - { label: "definition", name: "definition", widget: "string" }      
      - { label: "source", name: "source", widget: "string" }
      - { label: "year", name: "year", widget: "string" }
      - label: "author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: ["authorsList.*.name"]
        display_fields: ["authorsList.*.name"]
        value_field: "authorsList.*.name"
    - label: "Ranked collections"
      name: "ranked"
      widget: "list"
      allow_add: true
      fields:
      - label: "lesson type"
        name: "type"
        widget: "relation"
        collection: "enums"
        search_fields: ["questionTypes.*.name"]
        display_fields: ["questionTypes.*.name"]
        value_field: "questionTypes.*.name"
      - { label: "unit", name: "unit", widget: "string" }
      - { label: "unit description", name: "unitDescription", widget: "string" }
      - { label: "text", name: "text", widget: "string" }
      - { label: "list count", name: "listCount", widget: "number" }
      - label: "Items"
        label_singular: "Item"
        name: "items"
        widget: "list"
        allow_add: true
        fields:
        - { label: "rank", name: "rank", widget: "number" }
        - { label: "name", name: "name", widget: "string" }
        - { label: "value", name: "value", widget: "string" }
    - label: "Unranked collections"
      name: "unranked"
      widget: "list"
      allow_add: true
      fields:
      - { label: "unit", name: "unit", widget: "string" }
      - { label: "unit description", name: "unitDescription", widget: "string" }
      - { label: "text", name: "text", widget: "string" }
      - { label: "list count", name: "listCount", widget: "number" }
      - label: "Items"
        label_singular: "Item"
        name: "items"
        widget: "list"
        allow_add: true
        fields:
        - { label: "name", name: "name", widget: "string" }