backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Climate change cards"
    name: "climateCards"
  
    files:

    - label: "Cards"
      name: "cardList"
      file: "pages/cards/cards.json"
      widget: list
      allow_add: true      
      fields:
          - { label: "term", name: "term", widget: "string"}
          - { label: "definition", name: "definition", widget: "string"}
          - { label: "author", name: "author", widget: "string"}
          - { label: "source", name: "source", widget: "string"}
          - { label: "year", name: "year", widget: "datetime" }
          - { label: "Publish Date", name: "date", widget: "datetime" }