backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections:

  # Providers

  - label: "Providers"
    name: "providers"
    file: "pages/providers/providers.json"

    # fields:
    # - label: "providers file"
    #   name: "providersFile"      
    fields:
    - label: "providers"
      name: "providersList"
      widget: list
      allow_add: true
      fields:
          - { label: "name", name: "name", widget: "string"}
          - { label: "slug", name: "slug", widget: "string"}

  # Lessons

    - label: "lessons file"
      name: "lessonsFile"
      file: "pages/provider/[provider]/lessons/lessons.json"
      
      fields:
      - label: "lessons"
        name: "lessonList"
        widget: list
        allow_add: true
        fields:
            - { label: "provider", name: "title", widget: "string"}
            - { label: "title", name: "title", widget: "string"}
            - { label: "slug", name: "slug", widget: "string"}

  # Cards

    - label: "cards file" # Change to folder structure i.e. lesson/cards
      name: "cardsFile"
      file: "pages/provider/[provider]/lessons/[lesson]/cards.json"
      
      fields:
      - label: "cards"
        name: "cardList"
        widget: list
        allow_add: true
        fields:
              - { label: "term", name: "title", widget: "string"}
              - { label: "definition", name: "definition", widget: "string"}
              - { label: "author", name: "author", widget: "string"}
              - { label: "source", name: "source", widget: "string"}
              - { label: "year", name: "year", widget: "string" }
              - { label: "Publish Date", name: "date", widget: "datetime" }            