backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Cards sets"
    name: "cardSets"
  
    files:
    - label: "Card"
      name: "card"
      file: "pages/cards/cards.json"
      slug: "{{slug}}"
      fields:
        - label: 'Card list'
          name: "cardList"
          widget: list
          fields:
            - { label: "term", name: "title", widget: "string"}
            - { label: "definition", name: "title", widget: "string"}
            - { label: "author", name: "author", widget: "string"}
            - { label: "source", name: "source", widget: "string"}
            - { label: "year", name: "date", widget: "datetime" }
            - { label: "Publish Date", name: "date", widget: "datetime" }