backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections:

  - label: "Providers"
    name: providers

    files:

    - label: "providers container"
      name: "providersContainer"
      file: "pages/providers/providers.json"

      fields:
      - label: "providers"
        name: "providersList"

        widget: list
        allow_add: true
        fields:
            - { label: "name", name: "name", widget: "string"}
            - { label: "slug", name: "slug", widget: "string"}


    - label: "lessons container"
      name: "lessonsContainer"
      file: "pages/provider/[provider]/lessons/lessons.json"

      fields:
      - label: "lessons"
        name: "lessonsList"

        widget: list
        allow_add: true
        fields:
            - { label: "provider", name: "provider", widget: "string"}
            - { label: "title", name: "title", widget: "string"}
            - { label: "slug", name: "slug", widget: "string"}